
const TempGroupLoweringIntern = {
  /**
   * Schaltet die Absenkung für alle Gruppen AUS
   * 
   * @returns {void}
   */
  AllOff: function() {
    for (let i = 1; i < 10; i++) {
      this.SetLower(i, false);
    }
  },

  /**
   * Schaltet die Absenkung für alle Gruppen EIN
   * 
   * @returns {void}
   */
  AllOn: function() {
    for (let i = 1; i < 10; i++) {
      this.SetLower(i, true);
    }
  },

  /**
   * Ändert den Zustand der Absenkung und gibt eine Meldung aus
   * 
   * @param {number} listId - Id der Gruppen deren Absenkung geschaltet werden soll
   * @param {boolean} value - Zu schaltender Zustand (Ein/Aus)
   * @returns {void}
   */
  SetLower: function(listId, value) {
    let tagLower = `DB_Unified_HMILists_TempGroup[${listId}].Lowering`;
    let tagGroup = `DB_Unified_HMILists_TempGroup[${listId}].Group`;
  
    let ts = Tags.CreateTagSet([tagLower, tagGroup, "DB_User_CurrentUser_Name"]);
    ts.Read();
  
    let lower = ts[0].Value;
    let group = ts[1].Value;
    let user = ts[2].Value;
    
    if (group > 0) {
      let newLower;
  
      if (typeof value !== "undefined") {
        newLower = value == true;
      } else {
        newLower = !lower;
      }
  
      if (lower != newLower) {
        Tags(tagLower).Write(newLower);
    
        let id = newLower ? 7 : 8;
      
        HMIRuntime.Alarming.SysFct.CreateOperatorInputInformation(
            HMIRuntime.Resources.TextLists("@Default.MessageText").Item(id),
            user,
            group,
            HMIRuntime.Resources.TextLists("@Default.Groups")
          );
      }
    }
  }
}
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function Button_AllOff() {
  TempGroupLoweringIntern.AllOff();
}
export function Button_AllOn() {
  TempGroupLoweringIntern.AllOn();
}
export function Button_SetLower(listId, value) {
  TempGroupLoweringIntern.SetLower(listId, value);
}
