/**
 * Gibt an ob WinCC Unified auf dem Panel oder dem PC läuft
 *
 * @type {boolean}
 */
const isPanel = HMIRuntime.FileSystem.GetSpecialFolder(HMIRuntime.FileSystem.Enums.FolderId.HomeDir) == '/home/industrial/';



/**
 * Pfad zu den Rezepture Files
 *
 * @type {string}
 */
export const recipePath = isPanel ? '/media/simatic/data-storage/Recipes/' : 'C:\\Temp\\OS5m\\Data\\Recipes\\';

/**
 * Pfad zu den Text Files
 *
 * @type {string}
 */
export const textsPath = isPanel ? '/media/simatic/X51/weber/texts/' : 'C:\\Temp\\OS5m\\Data\\texts\\';

/**
 * Pfad zu den Text Update Filses über USB
 *
 * @type {string}
 */
export const textsUsbPath =  '/media/simatic/X61/texts/';

/**
 * Rezeptur-File für die Rezeptwerte
 *
 * @type {string}
 */
export const valueFile = recipePath + 'valueTable.csv';

/**
 * Rezeptur-File für die Rezeptverwaltung
 *
 * @type {string}
 */
export const recipeFile = recipePath + 'recipeTable.csv';



/**
 * File zum Merken der letzten Sprache
 *
 * @type {string}
 */
export const langFile = isPanel ? '/media/simatic/data-storage/language.bin' : 'C:\\Temp\\OS5m\\Data\\language.bin';


/**
 * File für das Ping-Script
 *
 * @type {string}
 */
export const pingScript = isPanel ? "/home/industrial/scriptPing.pl" : "C:\\Temp\\OS5m\\Home\\scriptPing.pl";

/**
 * Rezeptur-File für das DNS-Check-Script
 *
 * @type {string}
 */
export const dnsScript = isPanel ? "/home/industrial/scriptDNS.pl" : "C:\\Temp\\OS5m\\Home\\scriptDNS.pl";

/**
 * File zum Auswerten der letzen HMI-Änderung
 *
 * @type {string}
 */
export const hmiDownloaded = isPanel ? 'var/opt/siemens/automation/WinCCUnified/Projects/HMI_RT_1/currentConfiguration/deltas/deltaList' : 'C:\\ProgramData\\SCADAProjects\\HMI_RT_1-SIM\\currentConfiguration\\deltas\\deltaList';



/**
 * File für das Trend-Cookie
 *
 * @type {string}
 */
export const trendPath = isPanel ? '/media/simatic/data-storage/trendConfig.conf' : 'C:\\Temp\\OS5m\\Data\\trendConfig.conf';

/**
 * Pfad zum Exprotieren der Trend-Werte
 *
 * @type {string}
 */
export const trendExportPath = isPanel ? '/media/simatic/data-storage/trendexport/' : 'C:\\Temp\\OS5m\\Data\\trendexport\\';



/**
 * Pfad zum Speichern von Screenshots
 *
 * @type {string}
 */
export const screenshotPath = isPanel ? '/media/simatic/data-storage/screenshots/' : 'C:\\Temp\\OS5m\\Data\\screenshots\\';



/**
 * Pfad zum Speichern der NEXXT365URL
 *
 * @type {string}
 */
export const nexxt365File = isPanel ? '/media/simatic/data-storage/nexxt365.bin' : 'C:\\Temp\\OS5m\\Data\\nexxt365.bin';
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
